import os

class Config:
    AWS_DEFAULT_REGION = "us-east-1"
    AWS_COGNITO_DOMAIN = "localhost"
    AWS_COGNITO_USER_POOL_ID = os.environ.get("AWS_COGNITO_USER_POOL_ID")
    AWS_COGNITO_USER_POOL_CLIENT_ID = os.environ.get("AWS_COGNITO_USER_POOL_CLIENT_ID")
    AWS_COGNITO_USER_POOL_CLIENT_SECRET = os.environ.get("AWS_COGNITO_USER_POOL_CLIENT_SECRET")
    AWS_COGNITO_REDIRECT_URL = "localhost:5000/redirect"